name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd library
        ./gradlew buil
        cd ..
        npm install
